import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

    <div className="bg-gray-100">
    <nav className="container mx-auto">
        <ul className="flex py-3">
          <li className="flex py-3 pr-3"><Link href="/">Home</Link></li>
          <li className="flex py-3 px-3"><Link href="/about">About</Link></li>
          <li className="flex py-3 px-3"><Link href="/contact">Contact</Link></li>
          <li className="flex py-3 px-3"><Link href="/team">Team</Link></li>
        </ul>
      </nav>
    </div>

    <div className={inter.className}>
      
      <div className="container mx-auto">
        {children}
      </div>
      
    </div>

      </body>
    </html>
  );
}
